# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7f297af87182b12afb2946c675a575a438f558edeb0984b4d47fbe9c2b13922de9546947ffc5a31cae843edfaa7f3946a3a1dcee14c2de3bf02c646d1c24110

test:
  secret_key_base: c483d1976e66b292cc5e3f533ea66928a759f0b41e569ac7fb542bbec40b4804ae23b1823315a891bdd9c2fee0a44f9abaff3850d1c86b3838bb72f4782305a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
